# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92762f48bb9424236222196c33cc015e9427ec67ee929636464d0c61ed107581e04800bb109ebf5059ca1ae808c4154c416dfc260f0c6578f69b8f54d216dd52

test:
  secret_key_base: 37bc9dd9fab7b9f22730db7caebede1f4c847ffbd251f7d1d54153089e049dace6dd07614ab80c8a1bc7ddc0d159db3681678409b83f38ced91718a599baaa00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
